### PR TITLE
Web service examples: WMTS

### PR DESCRIPTION
**Pull request by dkillick**
Adds an IPython notebook that demonstrates plotting WMTS tiles using Cartopy and adding value by overlaying data from Iris cubes, etc.

This is a sister example to the WMS example in #7, and has a very similar structure. There's no coordinate transforms example in this as Cartopy doesn't yet have the capacity to do this (but see the linked Cartopy PR) but there is an example of changing the zoom level.

### CODE REVIEW

**Comment by dkillick** [comment]
Ping @gm-s @bjlittle :stuck_out_tongue_winking_eye:

**Comment by gm-s** [comment]
Pong @dkillick (Round trip time 3546ms)

**Comment by dkillick** [comment]
So far I've spotted that:
 * The link in the first paragraph of the introduction section is probably wrong, and
 * We can't transform but we can zoom, so the second bulleted list in the introduction section should be updated to reflect this.

**Comment by gm-s** [comment]
Again, looking at this from the perspective of (can a beginner use this) rather than as a proof-reader, this again works well.

I'm not sure about one section...

**Comment by gm-s** [comment]
"Let's demonstrate making an WMTS request with Cartopy and plotting the map image contained in the response. Let's use data from the **CONUS GOES IR Satellite** exposed as a WMS service.\n",
      "\n",
      "To make a WMS request in Cartopy, as with every WMS request, we provide a URL to a WMS server. This server provides a web map service, which may provide one or more layers of geographic phenomena. To complete the we need to also provide the name of the layer we're interested in, and to find the names of the available layers we need to refer to the get capabilities response from the WMS server.\n",

- This hasn't been updated from the original? Still references WMS and GOES, rather than WMTS and VIIRS.

**Comment by dkillick** [comment]
Whoops! There was a lot of duplication, copying and pasting going on here :wink:

**Comment by dkillick** [comment]
For info, the above commit addresses the copy/paste errors that @gm-s and I identified.

**Comment by bjlittle** [comment]
@dkillick 

`Plotting WMTS tiles`
* **2nd para, last sentence** - Yeah, you know what I'm going to mention here ... same as before!
* **In [20]** - It would be kinda nice to see these side by side ... does that work?

Your plots seem to be long and thin. 

If your going to subplot side by side in the last example you might want to make them more square or use a tight layout ... your choice. Perhaps you might want to zoom to a higher resolution over a smaller Washington area ...

The alpha contours overplotting a dark background don't really work ... perhaps swap to OSM?

**Comment by dkillick** [comment]
Review actions. Care to take another look @bjlittle?

**Comment by bjlittle** [comment]
@dkillick Great, thanks! :+1:

**Pull request merged**
