### PR TITLE
updating notebooks to work with modern python

### PR DESCRIPTION
**Pull request by HarriKeenan**
### Todo

- [x] Mark `aux_coord_factory.ipynb` as non-functional, and raise an issue to fully re-write later.
- [x]  Mark `ocean_buoy_gridding.ipynb` as non-functional, and raise an issue to fully re-write later.

### CODE REVIEW

**Comment by trexfeathers** [comment]
Just a quick note for anyone else: @HarriKeenan and I are working this together and a full description will be added in due course 🙂

**Review by trexfeathers — CHANGES_REQUESTED** [review]

**Review by trexfeathers — APPROVED** [review]
Thanks for your hard work on this @HarriKeenan 🏅

**Comment by bjlittle** [comment]
@HarriKeenan Awesome! 🔥🚀

**Comment by hdyson** [comment]
Thanks @HarriKeenan!  @mo-gill (who identified the issue) and I appreciate the work you put into this 👍

**Pull request merged**
