### PR TITLE
Web services examples: WMS

### PR DESCRIPTION
**Pull request by dkillick**
Added an IPython notebook that demonstrates plotting WMS images using Cartopy and adding value by overlaying data from Iris cubes, etc.

### CODE REVIEW

**Comment by dkillick** [comment]
@bjlittle @marqh @gm-s could you provide your thoughts?

**Comment by dkillick** [comment]
It's worth noting that the notebook I've pushed is a _draft_, not a final version.

**Comment by dkillick** [comment]
@bjlittle and I just discussed and proposed a reviewing strategy for notebooks in this repo:
 * We review on the rendered notebook given that the raw view provided by github is not up to scratch. 
 * Comments on text are referenced based on section title, paragraph number, (sentence number) and reference quote.
 * Comments on code are referenced on the `In[x]` element in which they occur.

**Comment by bjlittle** [comment]
@dkillick Great work! :smile: 

I can't add comments to individual lines, shame on GitHub, so I identify points-of-interest by section. Here are some initial thoughts ...

`Plotting WMS response images` 
* **1st para, last sentence** - perhaps you may want to provide a link for the user to follow to find out more about the GOES satellite e.g. http://www.goes.noaa.gov/sat-explanation.html
* **2nd para, last sentence** - should this sentence start as "*To complete the* **request** ..." and suggest that you split this sentence into two dropping the conjunction.
* **3rd para** - Make `OWSLib` a link to their documentation?
* You could mention that Cartopy handles the WMS request for you under the hood ... smoke and mirrors, nothing to see here guv'. The OWSLib example just demonstrates some of the mechanics of what might be going on underneath, but at the end of the day it's not a real concern for the user as we've abstracted that level of detail away from them.

`Pre-In [41]`
* **Last sentence** - "... *and define a* **convenience** *function* ..." ?

`Pre-In [42]`
* Add a one line sentence to explain what the cell is doing.

`In [23]`
* The text labels can easily get lost, so I'd opt to either increase the font size or use the matplotlib stroke effect on the text. See https://github.com/bjlittle/ams2015/blob/master/posters/cartopy-tephi/src/web/cwmts_phoenix.py ... adds a bit of connective tissue code (which may slightly dilute the intent of your example) ... your call!

`In [27]`
* Can we use a constraint here rather than opting for index space?

`In [34]`
* Can we have the layer on top (with alpha) over the contour? Probably not ...
* Yellow coastlines are a bit washed out ... switch to black? If you agree, then cascade this to all applicable plots.

`Transforming WMS layers`
* **2nd para, 1st sentence** - You use `getcapabilities` here but `get capabilities` elsewhere ... do we need to be consistent in usage?

Is it possible to show a sub plot, like an exploded inset (as we discussed) to show how the resolution of the layer changes?

I don't think that we should piggy back WMTS and WCS examples into this one, but keep them all as separate notebooks? Thoughts? 

That's all I've got just now. HTH :wink:

**Comment by dkillick** [comment]
Thanks @bjlittle, I've done some implementing. My comments on your comments...

> Can we have the layer on top (with alpha) over the contour?

Turns out we can't - looks like the added WMS image does not support transparency.

> Is it possible to show a sub plot, like an exploded inset

Also no I'm afraid - there isn't another layer at a higher zoom level. What you see is what you've got. Also the WMS image disappeared at the higher zoom level, but I will demonstrate this in the WMTS example.

> I don't think that we should piggy back WMTS and WCS examples into this one

Agreed!

**Comment by dkillick** [comment]
Review actions - @bjlittle's  comments have been addressed unless discussed further above.

**Comment by gm-s** [comment]
This is understandable from a 'beginners perspective', I've been able to use this to look at other data sets.

One note - the bounding box returned by the wms.boundingBoxWGS84 call is in a different order to what we're pushing to Cartopy. Design difference, or a bug in one or the other?

**Comment by dkillick** [comment]
> bounding box returned by the wms.boundingBoxWGS84 call is in a different order

No-one can decide on a common bounding-box order... I have to look up the argument order to `ax.set_extent` every time I use it!

**Comment by bjlittle** [comment]
@dkillick Looking good to me.

Two final (minor) points:
* Why not add a little more real-estate to the plots, say `(14, 9)` ... whatever looks best.
* **Introduction, 3rd para, last sentence** - You need to address `Increased detail at higher zoom levels is implemented... how?`

Otherwise :+1:

**Comment by dkillick** [comment]
Thanks @bjlittle I spotted the second bullet point earlier! I've also made a few other minor tweaks to things that I spotted along the way as I was preparing the WMTS example.

**Comment by bjlittle** [comment]
@dkillick Thanks! :+1:

**Pull request merged**
